sudo: false
addons:
  apt:
    packages:
      - aspell
      - aspell-en
language: perl
perl:
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
env:
  global:
    - COVERAGE=1
before_install:
  - cpanp x
  - eval $(curl https://travis-perl.github.io/init) --auto
